// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://edgxhgevaduxnxtfyyfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkZ3hoZ2V2YWR1eG54dGZ5eWZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNTQ0MzQsImV4cCI6MjA4NTYzMDQzNH0.hxGzgm9-eUl5v5E-fXPrXvboh-yi5y_DGsnhhkQhBt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
